-- MELHORIA: garante recriação limpa do banco (útil em testes)
DROP DATABASE IF EXISTS STREAMING;

-- MELHORIA: criação com charset UTF-8 moderno (utf8mb4 suporta emojis e todos caracteres)
CREATE DATABASE IF NOT EXISTS STREAMING
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_unicode_ci;

USE STREAMING;

CREATE TABLE IF NOT EXISTS USUARIO (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_ASSINATURA INT NOT NULL UNIQUE,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	SENHA_HASH VARCHAR(60) NOT NULL,
	CPF CHAR(11) NOT NULL UNIQUE,
	DATA_NASCIMENTO DATE NOT NULL,
	TELEFONE VARCHAR(15),
	DATA_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ATIVO TINYINT(1) NOT NULL DEFAULT 1,
    FOREIGN KEY (CODIGO_ASSINATURA) REFERENCES ASSINATURA (CODIGO)
);

CREATE TABLE IF NOT EXISTS PLANO (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_PLANO VARCHAR(45) NOT NULL,
	DESCRICAO VARCHAR(200),
	PRECO DECIMAL(10,2) NOT NULL,
	QUALIDADE_VIDEO ENUM('SD','HD','FULL_HD','4K') NOT NULL DEFAULT 'HD',
	LIMITE_TELAS SMALLINT NOT NULL DEFAULT 1,
	PERMITE_DOWNLOAD TINYINT(1) NOT NULL DEFAULT 0,
	ATIVO TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS GENERO (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_GENERO VARCHAR(45) NOT NULL UNIQUE,
	DESCRICAO VARCHAR(200),
	CATEGORIA VARCHAR(40),
	DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ATIVO TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS CONTEUDO (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
	TITULO VARCHAR(100) NOT NULL,
	SINOPSE TEXT,
	ANO_LANCAMENTO SMALLINT NOT NULL,
	CLASSIFICACAO_ETARIA ENUM('L','10','12','14','16','18') NOT NULL DEFAULT 'L',
	DATA_INCLUSAO_CATALOGO DATE NOT NULL,
	TIPO_CONTEUDO ENUM('FILME','SERIE') NOT NULL,
	TRAILER_URL VARCHAR(200),
	ATIVO TINYINT(1) NOT NULL DEFAULT 1
);

-- FILME é especialização de CONTEUDO -> a PK também é FK (herança por tabela)
-- Isso é o relacionamento 1:1 CONTEUDO x FILME e evita repetir título, sinopse, ano...
CREATE TABLE IF NOT EXISTS FILME (
	CODIGO INT PRIMARY KEY,
	DURACAO_MINUTOS SMALLINT NOT NULL,
	DIRETOR VARCHAR(100),
	ORCAMENTO DECIMAL(12,2),
	BILHETERIA DECIMAL(12,2),
	DATA_ESTREIA_CINEMA DATE,
	RESOLUCAO_MAXIMA ENUM('SD','HD','FULL_HD','4K') NOT NULL DEFAULT 'HD',
	IDIOMA_ORIGINAL VARCHAR(45),
	POSSUI_LEGENDA_PT TINYINT(1) NOT NULL DEFAULT 0,
	FOREIGN KEY (CODIGO) REFERENCES CONTEUDO (CODIGO)
);

-- SERIE também é especialização de CONTEUDO (1:1)
CREATE TABLE IF NOT EXISTS SERIE (
	CODIGO INT PRIMARY KEY,
	DATA_PRIMEIRA_EXIBICAO DATE,
	EMISSORA_ORIGINAL VARCHAR(100),
	PAIS_ORIGEM VARCHAR(60),
	STATUS_PRODUCAO ENUM('EM_ANDAMENTO','FINALIZADA','CANCELADA') NOT NULL DEFAULT 'EM_ANDAMENTO',
	CRIADOR VARCHAR(100),
	FOREIGN KEY (CODIGO) REFERENCES CONTEUDO (CODIGO)
);

-- Cada episódio pertence a uma única série (1:N)
CREATE TABLE IF NOT EXISTS EPISODIO (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
	CODIGO_SERIE INT NOT NULL,
	TITULO_EPISODIO VARCHAR(100) NOT NULL,
	NUMERO_TEMPORADA SMALLINT NOT NULL,
	NUMERO_EPISODIO SMALLINT NOT NULL,
	DURACAO_MINUTO SMALLINT,
	DATA_EXIBICAO DATE,
	SINOPSE TEXT,
	UNIQUE (CODIGO_SERIE, NUMERO_TEMPORADA, NUMERO_EPISODIO),
	FOREIGN KEY (CODIGO_SERIE) REFERENCES SERIE (CODIGO)
);

-- Resolve o relacionamento N:N CONTEUDO x GENERO (chave primária composta)
CREATE TABLE IF NOT EXISTS CONTEUDO_GENERO (
	CODIGO_CONTEUDO INT,
	CODIGO_GENERO INT,
	PRINCIPAL TINYINT(1) NOT NULL DEFAULT 0,
	PESO_RELEVANCIA DECIMAL(4,2) NOT NULL DEFAULT 1.00,
	DATA_VINCULACAO DATE NOT NULL,
	OBSERVACAO VARCHAR(100),
	ATIVO TINYINT(1) NOT NULL DEFAULT 1,
	FOREIGN KEY (CODIGO_CONTEUDO) REFERENCES CONTEUDO (CODIGO),
	FOREIGN KEY (CODIGO_GENERO) REFERENCES GENERO (CODIGO),
	PRIMARY KEY (CODIGO_CONTEUDO, CODIGO_GENERO)
);

-- Um usuário pode ter vários perfis (1:N)
CREATE TABLE IF NOT EXISTS PERFIL (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
	CODIGO_USUARIO INT NOT NULL,
	NOME_PERFIL VARCHAR(45) NOT NULL,
	TIPO_PERFIL ENUM('ADULTO','INFANTIL') NOT NULL DEFAULT 'ADULTO',
	CLASSIFICACAO_ETARIA_MAX ENUM('L','10','12','14','16','18') NOT NULL DEFAULT '18',
	IDIOMA_PREFERIDO VARCHAR(10) NOT NULL DEFAULT 'pt-BR',
	DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ATIVO TINYINT(1) NOT NULL DEFAULT 1,
	UNIQUE (CODIGO_USUARIO, NOME_PERFIL),
	FOREIGN KEY (CODIGO_USUARIO) REFERENCES USUARIO (CODIGO)
);

-- Equipamentos cadastrados pelo usuário (1:N)
CREATE TABLE IF NOT EXISTS DISPOSITIVO (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
	CODIGO_USUARIO INT NOT NULL,
	TIPO_DISPOSITIVO VARCHAR(30) NOT NULL,
	MODELO VARCHAR(60),
	SISTEMA_OPERACIONAL VARCHAR(40),
	DATA_ULTIMO_ACESSO DATETIME,
	ATIVO TINYINT(1) NOT NULL DEFAULT 1,
	FOREIGN KEY (CODIGO_USUARIO) REFERENCES USUARIO (CODIGO)
);

-- FORMA_PAGAMENTO - formas de pagamento do usuário (1:N)
CREATE TABLE IF NOT EXISTS FORMA_PAGAMENTO (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
	CODIGO_USUARIO INT NOT NULL,
	TIPO_PAGAMENTO ENUM('CARTAO_CREDITO','PIX','BOLETO') NOT NULL,
	NOME_TITULAR VARCHAR(100),
	ULTIMOS_DIGITOS CHAR(4),
	BANDEIRA VARCHAR(30),
	DATA_VALIDADE DATE,
	STATUS TINYINT(1) NOT NULL DEFAULT 1,
	DATA_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (CODIGO_USUARIO) REFERENCES USUARIO (CODIGO)
);

-- Relacionamento 1:1 com USUARIO e N:1 com PLANO
-- UNIQUE em CODIGO_USUARIO garante o 1:1 (cada usuário tem UMA assinatura)
CREATE TABLE IF NOT EXISTS ASSINATURA (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
	CODIGO_PLANO INT NOT NULL,
	CODIGO_ASSINATURA VARCHAR(30) NOT NULL UNIQUE,
	DATA_INICIO DATE NOT NULL,
	DATA_FIM DATE,
	STATUS_ASSINATURA ENUM('ATIVA','SUSPENSA','CANCELADA') NOT NULL DEFAULT 'ATIVA',
	RENOVACAO_AUTOMATICA TINYINT(1) NOT NULL DEFAULT 1,
	FOREIGN KEY (CODIGO_PLANO) REFERENCES PLANO (CODIGO)
);

-- PAGAMENTO gerado pela assinatura (1:N) e quitado por uma forma (1:N)
-- PAGAMENTO não repete o preço do plano nem os dados da forma de pagamento: esses valores são obtidos pelas chaves estrangeiras (3FN)
CREATE TABLE IF NOT EXISTS PAGAMENTO (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
	CODIGO_FORMA_PAGAMENTO INT NOT NULL,
	DATA_PAGAMENTO DATETIME,
	DATA_VENCIMENTO DATE NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	STATUS_PAGAMENTO ENUM('PENDENTE','APROVADO','RECUSADO','ESTORNADO') NOT NULL DEFAULT 'PENDENTE',
	CODIGO_TRANSACAO VARCHAR(60) UNIQUE,
	FOREIGN KEY (CODIGO_FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO (CODIGO)
);

-- Resolve o relacionamento N:N PERFIL x CONTEUDO (histórico de exibição).
-- A PK é simples porque o mesmo par perfil/conteúdo se repete ao longo do tempo.
CREATE TABLE IF NOT EXISTS HISTORICO_VISUALIZACAO (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
	CODIGO_PERFIL INT NOT NULL,
	CODIGO_CONTEUDO INT NOT NULL,
	DATA_HORA_INICIO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DATA_HORA_FIM DATETIME,
	TEMPO_ASSISTIDO_SEG INT NOT NULL DEFAULT 0,
	PERCENTUAL_PROGRESSO DECIMAL(5,2) NOT NULL DEFAULT 0,
	CONCLUIDO TINYINT(1) NOT NULL DEFAULT 0,
	ORIGEM_ACESSO VARCHAR(30),
	FOREIGN KEY (CODIGO_PERFIL) REFERENCES PERFIL (CODIGO),
	FOREIGN KEY (CODIGO_CONTEUDO) REFERENCES CONTEUDO (CODIGO)
);

-- Resolve o relacionamento N:N PERFIL x CONTEUDO (avaliação).
-- UNIQUE porque cada perfil dá apenas UMA nota por conteúdo.
CREATE TABLE IF NOT EXISTS AVALIACAO (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
	CODIGO_PERFIL INT NOT NULL,
	CODIGO_CONTEUDO INT NOT NULL,
	NOTA DECIMAL(3,1) NOT NULL,
	COMENTARIO TEXT,
	DATA_AVALIACAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	RECOMENDA TINYINT(1) NOT NULL DEFAULT 1,
	UNIQUE (CODIGO_PERFIL, CODIGO_CONTEUDO),
	FOREIGN KEY (CODIGO_PERFIL) REFERENCES PERFIL (CODIGO),
	FOREIGN KEY (CODIGO_CONTEUDO) REFERENCES CONTEUDO (CODIGO)
);

-- Resolve o relacionamento N:N PERFIL x CONTEUDO (lista de favoritos)
CREATE TABLE IF NOT EXISTS MINHA_LISTA (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
	CODIGO_PERFIL INT NOT NULL,
	CODIGO_CONTEUDO INT NOT NULL,
	DATA_ADICAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIORIDADE SMALLINT NOT NULL DEFAULT 1,
	NOTIFICAR_LANCAMENTO TINYINT(1) NOT NULL DEFAULT 0,
	UNIQUE (CODIGO_PERFIL, CODIGO_CONTEUDO),
	FOREIGN KEY (CODIGO_PERFIL) REFERENCES PERFIL (CODIGO),
	FOREIGN KEY (CODIGO_CONTEUDO) REFERENCES CONTEUDO (CODIGO)
);