USE SUPERMERCADO;

SELECT CPF, CODIGO
FROM CLIENTE;

SELECT UF
FROM PESSOA;

SELECT CIDADE, UF
FROM PESSOA;

SELECT DISTINCT CIDADE, UF
FROM PESSOA;

SELECT DISTINCT CIDADE AS CITY, UF AS STATE
FROM PESSOA;

SELECT DISTINCT CIDADE AS CITY, UF AS STATE -- SELECIONAR COLUNAS
FROM PESSOA -- SELECIONAR TABELAS
WHERE UF = 'DF'; -- SELECIONAR LINHAS

SELECT NOME AS NOME_PESSOA, LOGRADOURO, CEP
FROM PESSOA
WHERE LOGRADOURO = 'Rua C';

SELECT NOME, LOGRADOURO, CEP
FROM PESSOA
WHERE LOGRADOURO = 'Rua C' AND CODIGO = 1;

-- VER CONTEÚDOS SOBRE OPERADORES ARITMÉTICOS, COMPARACIONAIS E LÓGICOS --