USE SUPERMERCADO;

UPDATE PESSOA
SET NOME = 'Sophia Freeman', UF = 'GO'
WHERE CODIGO = 3;

UPDATE PESSOA
SET LOGRADOURO = 'Rua C', CIDADE = 'Taguatinga'
WHERE CODIGO = 1;

UPDATE LOGIN
SET USUARIO = 'SIQ', SENHA_HASH = 146
WHERE CODIGO = 1;

UPDATE LOGIN
SET USUARIO = 'FRE', SENHA_HASH = 732
WHERE CODIGO = 2;