-- MELHORIA: garante recriação limpa do banco (útil em testes)
DROP DATABASE IF EXISTS SUPERMERCADO;

-- MELHORIA: criação com charset UTF-8 moderno (utf8mb4 suporta emojis e todos caracteres)
CREATE DATABASE IF NOT EXISTS SUPERMERCADO
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_unicode_ci;

USE SUPERMERCADO;

CREATE TABLE IF NOT EXISTS PESSOA (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL, 
	LOGRADOURO VARCHAR(120), 
	CIDADE VARCHAR(60) NOT NULL,
	UF CHAR(2) NOT NULL,
	CEP VARCHAR(9),
	EMAIL VARCHAR(100) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS LOGIN (
    CODIGO INT PRIMARY KEY,
    USUARIO VARCHAR(40) NOT NULL,
    SENHA_HASH VARCHAR(60) NOT NULL, 
    ULTIMO_ACESSO DATETIME,
    FOREIGN KEY (CODIGO) REFERENCES PESSOA (CODIGO)
);

CREATE TABLE IF NOT EXISTS CLIENTE (
    CODIGO INT PRIMARY KEY,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    DATA_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CODIGO) REFERENCES PESSOA (CODIGO)
);

CREATE TABLE IF NOT EXISTS VENDEDOR (
    CODIGO INT PRIMARY KEY,
    CNPJ VARCHAR(18) NOT NULL UNIQUE, 
    SALARIO DECIMAL(10,2) NOT NULL, 
    FAIXA_COMISSAO ENUM ('A','B','C','D') NOT NULL,
    ATIVO TINYINT(1) NOT NULL DEFAULT 1,
    FOREIGN KEY (CODIGO) REFERENCES PESSOA (CODIGO)
);

CREATE TABLE IF NOT EXISTS PEDIDO (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_CLIENTE INT,
    CODIGO_VENDEDOR INT,
    DATA_PEDIDO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONFIRMADO TINYINT(1) NOT NULL DEFAULT 0,
    VALOR_TOTAL DECIMAL(10,2),
    FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE (CODIGO),
    FOREIGN KEY (CODIGO_VENDEDOR) REFERENCES VENDEDOR (CODIGO)
);

CREATE TABLE IF NOT EXISTS PRODUTO (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(200),
    PRECO_BASE DECIMAL(10,2) NOT NULL,
    ESTOQUE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ITEM_PEDIDO (
	CODIGO_PEDIDO INT,
    CODIGO_PRODUTO INT,
    QUANTIDADE INT NOT NULL DEFAULT 0,
    PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
    SUBTOTAL DECIMAL(10,2),
    FOREIGN KEY (CODIGO_PEDIDO) REFERENCES PEDIDO (CODIGO),
    FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO (CODIGO),
    PRIMARY KEY (CODIGO_PEDIDO, CODIGO_PRODUTO)
);

CREATE TABLE IF NOT EXISTS IMAGEM (
	CODIGO_PRODUTO INT,
    NUMERO_IMAGEM INT,
    URL VARCHAR(200) NOT NULL,
    DESCRICAO VARCHAR(200),
    FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO (CODIGO),
    PRIMARY KEY (CODIGO_PRODUTO, NUMERO_IMAGEM)
);

CREATE TABLE IF NOT EXISTS HISTORICO_SALARIO (
	CODIGO INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_VENDEDOR INT NOT NULL,
    NOME_VENDEDOR VARCHAR(100),
    SALARIO_ANTIGO DECIMAL(10,2),
    SALARIO_NOVO DECIMAL(10,2),
    DATA_HORA_ALTERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);